=== Javacream/org.javacream.training.java.experts/org.javacream.training.java.experts.units/target/classes/org/javacream/training/java/experts/xml/publisher.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.javacream.org/publisher"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.javacream.org/publisher">
	<element name="publisher" type="tns:publisherType"></element>
	<element name="book" type="tns:bookType"></element>

	<complexType name="publisherType">
		<sequence>
			<element name="book" type="tns:bookType" maxOccurs="unbounded"
				minOccurs="1"></element>
		</sequence>
		<attribute name="name" type="string"></attribute>
		<attribute name="city" type="string"></attribute>
	</complexType>
	<complexType name="bookType">
		<sequence>
			<element name="isbn" type="string" nillable="false"></element>
			<element name="title" type="string" nillable="false"></element>
			<element name="price">
				<simpleType>
					<restriction base="double">
						<minExclusive value="0"></minExclusive>
					</restriction>
				</simpleType>
			</element>
		</sequence>
	</complexType>
</schema>

=== Javacream/org.javacream.training.java.experts/org.javacream.training.java.experts.units/src/org/javacream/training/java/experts/xml/publisher.xml
<?xml version="1.0" encoding="UTF-8"?>
<publisher xmlns="http://www.javacream.org/publisher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.javacream.org/publisher publisher.xsd " name="Springer" city="Berlin">
	<book>
		<isbn>ISBN1</isbn>
		<title>Java in Action</title>
		<price>19.99</price>
	</book>
	<book>
		<isbn>ISBN2</isbn>
		<title>Apache Commons</title>
		<price>9.99</price>
	</book>
	<book>
		<isbn>ISBN3</isbn>
		<title>Spring Framework</title>
		<price>25.99</price>
	</book>
</publisher>
